# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookEntity')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Library')),
            ],
        ),
        migrations.CreateModel(
            name='AddUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.LibUser')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(auto_now=True)),
                ('date_to', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookEntity')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.LibUser')),
            ],
        ),
    ]
